### ISSUE TITLE
Agencies (possibly also other modules): rich text fields loose focus

### ISSUE THREAD

**Issue by ctueck** [EQAR/deqar_frontend#83] opened 2021-03-24 16:48 UTC
While writing into the rich text fields (happens at least for "Specialisation Note" in agencies) the field randomly looses focus. It's particularly annoying while one is editing, hitting backspace and instead of deleting text in the field the browser interprets this like the back button. :) (Hence potentially loosing changes...)

**Comment by JoshBone** [comment] 2021-11-23 21:43
I'm closing this, because I wasn't able to reproduce it and if I remember correctly this seemed to be gone after updating the editor.

**Closed as completed by JoshBone** 2021-11-23 21:43 UTC
Labels: bug
